#ifndef FS_PROGRAMS_H
#define FS_PROGRAMS_H

#include <stdint.h>

/*
 * Table of ELF programs embedded in the kernel image (generated by the
 * Makefile from PROGRAMS).  fs_init() copies each one into /bin in the memfs.
 */
struct embedded_program {
  const char *name;
  const uint8_t *start;
  const uint8_t *end;
};

extern const struct embedded_program embedded_programs[];
extern const uint32_t embedded_program_count;

/*
 * Names that are hardlinked to the multicall "toybox" program in /bin.  toybox
 * dispatches on argv[0], so one embedded binary serves every applet.
 */
extern const char *const embedded_applets[];
extern const uint32_t embedded_applet_count;

#endif
